steps:

- name: gcr.io/cloud-builders/npm
  args: [ install ]

- name: gcr.io/cloud-builders/npm
  args: [ run, build, --prod ]

- name: ubuntu
  entrypoint: bash
  args:
  - -c
  - |
    mkdir ./gae-flex/static/

- name: ubuntu
  entrypoint: bash
  args:
  - -c
  - |
    cp -rf ./dist/gcp-cloudbuild-gae-flex-angular/ ./gae-flex/static/

- name: gcr.io/cloud-builders/gcloud
  args: [ 'app', 'deploy', './gae-flex/app.yaml', '--version=1' ]
