steps:

- name: 'gcr.io/cloud-builders/npm'
  args: [ 'install' ]

- name: 'gcr.io/cloud-builders/npm'
  args: [ 'run', 'build', '--prod' ]

- name: 'ubuntu'
  entrypoint: 'bash'
  args:
  - '-c' # pass what follows as a command to bash
  - |
    sed $'s/^M$//' ./build-helpers/copy-dist-files-to-gae.sh > sh # ignore CR (\r) chars when reading the script file

- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'app', 'deploy', './gae-flex/app.yaml', '--version=1' ]
